spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: "git"
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/aj-octy/micro-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: 12345678901234567890123456789012

server:
    port: 8071