spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: accounts-service
              uri: http://localhost:8081
              predicates:
                - Path=/accounts/**
              filters:
                - StripPrefix=1
            - id: loans-service
              uri: http://localhost:8090
              predicates:
                - Path=/loans/**
            - id: cards-service
              uri: http://localhost:9000
              predicates:
                - Path=/cards/**
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
