spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
        git:
          uri: "https://github.com/aj-octy/config-server-files.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          basedir: /tmp/config-repo
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "875GHMBJSK98769759GJH768KJ79"

server:
  port: 8071

logging:
  level:
    org.springframework.cloud.config.server.environment: DEBUG
